name: Clean React

on:
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install packages
      run: yarn
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test:coveralls;
        
          
          
